### ISSUE TITLE
Hoymiles

### ISSUE THREAD

**Issue by trombose009** [atc1441/NETSGPClient#20] opened 2022-08-16 16:47 UTC
Hi, 

Is there a chance that it works with hoymiles too?

Would you analyze a hoymiles If I send it to you?

**Comment by atc1441** [comment] 2022-08-16 17:17
Please take a look at this:

https://www.mikrocontroller.net/topic/525778

It is already reversed if its the same model👍

**Comment by enwi** [comment] 2022-08-17 09:55
Duplicate of #6

**Closed as completed by enwi** 2022-08-17 09:55 UTC
Labels: duplicate
